# version: "3.8" // Modern Docker (V2) auto process files using standars --> version ... = trigger deprecation warnings !!
services:
  rabbitmq:
    # image: rabbitmq:3-management // --> rabbitmq:3.13-management-alpine (ALPINE  reduces image size and vulnerabilities)
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672" 
      - "15672:15672" 
      # Secured Credentials via Variables
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      # Added Data & Log Persistence
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    # Configured Resource Limits
    networks:
      - amqp-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
    # Implemented an Active Health Check
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  rabbitmq_data:
  rabbitmq_logs:

networks:
  amqp-network:
    driver: bridge